### ISSUE TITLE
Frontend [question]

### ISSUE THREAD

**Issue by milan090** [zero-to-mastery/ascii-art#1]
How about having a frontend with React where you can:
1. Select and upload image
2. Apply different filters (not just ascii-art)
3. Have color options too.

**Comment by MehulGupta21** [comment]
Hi Milan090, it's a great idea I think why not add some gradient and other symbols in it to make it more attractive.

**Comment by MattCSmith** [comment]
Like the idea @milan090 but before we go down this route, can we do this in a way that wont prevent collaborations from those that do not know React. 

Perhaps we create a new folder and create another version?

**Comment by milan090** [comment]
@MattCSmith yes, but I think it will also be great a great chance for people to work with React and Python backend at the same time. If they know only Python they can do the backend part, if they know React do the frontend. But yeah as you suggested making a different version would be also good. Or make a different repo?

**Comment by nikhilchintawar** [comment]
@MattCSmith yes we can create the new folder. @milan090  did you created the new folder? and are we going to use only react or react/redux

**Comment by milan090** [comment]
@nikhilchintawar not yet. Thought to do after deciding with the team. React/Redux. I think that would be perfect for this Project.

**Comment by singhana7272** [comment]
@MattCSmith can i add a new file where I will be converting images into ascii art using pillow as well as numpy module..

**Comment by MattCSmith** [comment]
Apologies for my late response. 
As long as Python only devs still have the opportunity to work on this project I am happy for this to proceed.

**Comment by milan090** [comment]
Alright @MattCSmith I'll go ahead and create a folder for React and also a branch for prs related to it. What would the backend be on? Django?

**Comment by nikhilchintawar** [comment]
@milan090 yes we can use the django

**Comment by milan090** [comment]
@nikhilchintawar Ok we can discuss further on discord

**Comment by peteruche21** [comment]
ouch and am just coming here to see this after i've made a pr with flask
no issues i can still  join in
