### ISSUE TITLE
about creating new folder

### ISSUE THREAD

**Issue by nikhilchintawar** [zero-to-mastery/ascii-art#13]
@MattCSmith can I create a new folder and in that use react as frontend and Django as a backend for creating a full-stack app.

**Comment by MattCSmith** [comment]
@nikhilchintawar apologies for the delay and my ignorance as I am not a Python developer. 
Isn't this a duplicate of #1 ?

**Comment by nikhilchintawar** [comment]
yes sorry I thought he was just asking for frontend I will close this issue.
