### ISSUE TITLE
Unused method has undeclarared reference

### ISSUE THREAD

**Issue by ndeoligence** [zero-to-mastery/ascii-art#23]
https://github.com/zero-to-mastery/ascii-art/blob/5481f4daa47f73ae87507874d03076badd01913e/community-version.py#L53

The method `write_image_to_text_file` references an undeclared variable `image_file_path`. Either this should be declared in the signature or the method removed, since it doesn't get called.

**Comment by AnastasiaCortes** [comment]
Variable image_file_path is a global scope variable.  It gets assigned when you run the file (image_file_path = sys.argv[1])

**Comment by ndeoligence** [comment]
Thanks @AnastasiaCortes - It was an issue in my local state
