### ISSUE TITLE
User messages in web version (Flask)

### ISSUE THREAD

**Issue by ndeoligence** [zero-to-mastery/ascii-art#72]
The Flask app (under web version) has a few messages it prints to the console, which gives the user useful feedback on their actions. We need to move these to the browser (via flash messages) since the users wouldn't have access to the terminal to see them when deployed

**Comment by rpdavila** [comment]
Done! check for consistency, please.

**Comment by rpdavila** [comment]
> The Flask app (under web version) has a few messages it prints to the console, which gives the user useful feedback on their actions. We need to move these to the browser (via flash messages) since the users wouldn't have access to the terminal to see them when deployed

Done! Just requested a pull merge

**Comment by rpdavila** [comment]
@ndeoligence thoughts on the new changes? Or you can say they are old now because a lot has changed, and it may be better to not do the merge at all.

**Comment by ndeoligence** [comment]
Well, I was especially keen on the flask messages - we're still printing to the console. Lol.
But I get that it'll probably be a lot of work merging the current project state into your pending PR, so I'll leave it to you to make the call

**Comment by rpdavila** [comment]
ill find a workaround to this problem. delte the old one and I will create a new one with the new modifications

**Comment by ndeoligence** [comment]
@rpdavila well done (and thanks) for getting this done!
