### ISSUE TITLE
Supported image types message

### ISSUE THREAD

**Issue by ndeoligence** [zero-to-mastery/ascii-art#73]
Although this is in the web version (Flask app), the changes only require python knowledge, and not Flask.

We need to replace the message **only png files are accepted** in `web version/app.py` with a formatted string version that gets the supported types from the configuration: ALLOWED_IMAGE_EXTENSIONS.

**Comment by bhatt01tapasvi** [comment]
I want to start working on this.

**Comment by Cdambrain** [comment]
Is this issue still opened? Why 'closed this in #76 on 25 Oct 2020' and 'reopened this on 3 Nov 2020'?
